### ISSUE TITLE
Visual Recognition Documentation - Getting Started Java examples are broken/incorrect

### ISSUE THREAD

**Issue by derekteay** [IBM-Bluemix-Docs/visual-recognition#101]
Hi, I was helping at a hackathon this weekend and found that there are numerous issues with the Getting Started page for Visual Recognition - https://github.com/IBM-Bluemix-Docs/visual-recognition/blob/master/getting-started.md

I am using Java 8 with IntelliJ IDEA.

* The Maven and Gradle dependencies are incorrect, please see this page for the correct information - https://github.com/watson-developer-cloud/java-sdk#installation

  * Specifically for the Gradle example, you need to change this:
  ```
  compile 'com.ibm.watson.developer_cloud:java-sdk:{version}'
  ```
  * To this:
  ```
  compile 'com.ibm.watson:ibm-watson:7.1.1'
  ```

* The 3 examples include various syntax, type, and code errors. The example code also doesn't show the correct imports needed to run this code, though IntelliJ does give the correct suggestions, it might be nice to include that for completeness. Here is a rundown of the errors:

  * `Classify an image`, `Classify with the Food model` and `Detect faces in an image` all have the following code issues:
    ```java
    ClassifiedImages result = visualRecognition.classify(classifyOptions).execute();
    ```
    * This is the incorrect type and should be:
    ```java
    Response<ClassifiedImages> result = visualRecognition.classify(classifyOptions).execute();
    ```

    * This also has to be changed, otherwise it won't print the contents of the object:
    ```java
    System.out.println(result);
    ```
    * Change to:
    ```java
    System.out.println(result.getResult());
    ```

  * `Classify with the Food model` and `Detect faces in an image` have a `;` at the end of the line where there shouldn't be (because there is additional parameters that have to be added to this code), causing a compile error:
    ```java
    .url("https://watson-developer-cloud.github.io/doc-tutorial-downloads/visual-recognition/fruitbowl.jpg");
    ```

  * `Detect faces in an image` has non-Java code in the example:
    ```java
    var VisualRecognitionV3 = require('watson-developer-cloud/visual-recognition/v3');
    
    var visualRecognition = new VisualRecognitionV3({
      version: '2018-03-19',
      iam_apikey: 'O_tRmC_u1t9AXmG9U5UFIaWm8ZtU4m6N_i_8BhSE0zED'
    });
    ```

Below is the complete `java` file I wrote that has working examples and some extra debugging info to the console for clarity:

```java
import com.ibm.cloud.sdk.core.http.Response;
import com.ibm.cloud.sdk.core.service.security.IamOptions;
import com.ibm.watson.visual_recognition.v3.VisualRecognition;
import com.ibm.watson.visual_recognition.v3.model.ClassifiedImages;
import com.ibm.watson.visual_recognition.v3.model.ClassifyOptions;
import com.ibm.watson.visual_recognition.v3.model.DetectFacesOptions;
import com.ibm.watson.visual_recognition.v3.model.DetectedFaces;

import java.util.Arrays;

public class VisualRecognitionExamples {
    public static void main (String[] args) {
        VRImageClassification();
        VRFoodClassification();
        VRFaceDetection();
    }

    public static void VRImageClassification(){
        IamOptions options = new IamOptions.Builder()
                .apiKey("your-api-key-here")
                .build();

        VisualRecognition visualRecognition = new VisualRecognition("2018-03-19", options);

        ClassifyOptions classifyOptions = new ClassifyOptions.Builder()
                .url("https://watson-developer-cloud.github.io/doc-tutorial-downloads/visual-recognition/640px-IBM_VGA_90X8941_on_PS55.jpg")
                .build();
        Response<ClassifiedImages> result = visualRecognition.classify(classifyOptions).execute();
        System.out.println("\n******** VRImageClassification ********\n" + result.getResult() + "\n******** END VRImageClassification ********\n");
    }

    public static void VRFoodClassification(){
        IamOptions options = new IamOptions.Builder()
                .apiKey("your-api-key-here")
                .build();

        VisualRecognition visualRecognition = new VisualRecognition("2018-03-19", options);

        ClassifyOptions classifyOptions = new ClassifyOptions.Builder()
                .url("https://watson-developer-cloud.github.io/doc-tutorial-downloads/visual-recognition/fruitbowl.jpg")
                .classifierIds(Arrays.asList("food"))
                .build();
        Response<ClassifiedImages> result = visualRecognition.classify(classifyOptions).execute();
        System.out.println("\n******** VRFoodClassification ********\n" + result.getResult() + "\n******** END VRFoodClassification ********\n");
    }

    public static void VRFaceDetection(){
        IamOptions options = new IamOptions.Builder()
                .apiKey("your-api-key-here")
                .build();

        VisualRecognition visualRecognition = new VisualRecognition("2018-03-19", options);

        DetectFacesOptions detectFacesOptions = new DetectFacesOptions.Builder()
                .url("https://watson-developer-cloud.github.io/doc-tutorial-downloads/visual-recognition/Ginni_Rometty_at_the_Fortune_MPW_Summit_in_2011.jpg")
                .build();
        Response<DetectedFaces> result = visualRecognition.detectFaces(detectFacesOptions).execute();
        System.out.println("\n******** VRFaceDetection ********\n" + result.getResult() + "\n******** END VRFaceDetection ********\n");
    }
}
```

2 more things worth noting:

* There is another documentation page for Visual Recognition that has some info correct, some information that is different, and some code that will give compiler errors for the reasons outlined above. It might be good to combine these pages so that information stays up-to-date without needed duplicate changes: https://cloud.ibm.com/apidocs/visual-recognition?code=java

* The participant was trying to do this within Android Studio and we eventually got it working, however, there is a modification that needs to be made to the Gradle file, otherwise the solution will not compile and run, due to errors thrown by Google's libraries. Note where it says `implementation` instead of `compile` when building this for Android, you can read why here: https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle

  This isn't exactly relevant to the pure Java example (although you can use `implementation` instead of `compile` outside of building for Android), but since there is no `Mobile` section, it might be good to note (or maybe create it's own section):
  ```
  implementation('com.ibm.watson:ibm-watson:7.1.1') {
          exclude group: 'com.google.code.findbugs', module: 'annotations'
  }
  ```

**Comment by SirSpidey** [comment]
@derekteay Thanks for pointing this out. We're working on the update.
