### ISSUE TITLE
cURL 401 Unauthorized

### ISSUE THREAD

**Issue by SkyTianTian** [IBM-Bluemix-Docs/visual-recognition#104]
In my CURL, I used the same KEY from a "Classify" model under the same project. Should I apply for another KEY?

**Comment by SirSpidey** [comment]
@SkyTianTian, API keys are service specific. You can find information about how to find the API key at https://cloud.ibm.com/docs/services/visual-recognition?topic=visual-recognition-getting-started-tutorial. 

If you have other questions about how to use the service or API keys, feel free to post to [IBM Developer Answers](https://developer.ibm.com/answers/topics/visual-recognition.html).

**Comment by SkyTianTian** [comment]
@SirSpidey  I have fixed the API program, but know it turns to 404, I attached my curl code here and can you roughly take a look to see what might be a problem:

curl -X POST -u "apikey:O......n" -F "features=objects" -F "collection_ids=2a82d179-5ee3-450f-b348-5b1202d511d5" -F "threshold=0.35" -F "images_file=@honda.png" "https://gateway.watsonplatform.net/visual-recognition/api/v4/analyze?version=2019-02-11" 

Thanks again for your help

**Comment by SirSpidey** [comment]
@SkyTianTian Have you registered for the private beta for v4, Custom Object Detection? 
- If you have not registered, you cannot make calls to this API (you can use v3). You can request access at this link: https://datasciencex.typeform.com/to/c70Ak5. 
- If you have registered and have access to Custom Object Detection, you are missing some information from the call that allows you access. Please follow up with the contact person listed in the welcome email.
