### ISSUE TITLE
Building classifiers with the tool link to YouTube is out of date

### ISSUE THREAD

**Issue by rodalton** [IBM-Bluemix-Docs/visual-recognition#57]
The 'Building classifiers with the tool' video referred to from the TOC is significantly out of date. Consider replacing with this https://ibm.box.com/s/6hw1sg1l8wm2uup43zcfjtfrpf978xqk

**Comment by SirSpidey** [comment]
Thanks for the reminder about the video, @rodalton. I've removed the video and will work with the product team to get a more up-to-date video out there.

**Comment by rodalton** [comment]
Cool, thanks @SirSpidey 

I've just had this Visual Recognition video published on IBM Code, could be a fit for the product team? https://developer.ibm.com/code/techtalks/take-depth-tour-watson-visual-recognition-tooling-available-watson-studio/

Ronan

**Comment by SirSpidey** [comment]
@rodalton Have updated the docs to use that video on Youtube. Just waiting for a review and will get it out.
